In [37]:
# nahranie datasetu cez API 
import eurostat 

df = eurostat.get_data_df('gov_10a_exp')
df

,freq,unit,sector,cofog99,na_item,geo\TIME_PERIOD,1990,1991,1992,1993,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,A,MIO_EUR,S13,GF01,D1,AT,NaN,NaN,NaN,NaN,...,5266.5,5364.3,5512.1,5689.4,5760.8,5962.0,6173.0,6397.1,6665.7,6955.2
1,A,MIO_EUR,S13,GF01,D1,BE,NaN,NaN,NaN,NaN,...,8448.8,8562.7,8611.3,8849.4,9000.7,9045.2,9417.9,9836.9,10259.3,10878.3
2,A,MIO_EUR,S13,GF01,D1,BG,NaN,NaN,NaN,NaN,...,405.6,449.8,474.7,492.5,518.6,572.8,691.7,690.7,860.4,871.4
3,A,MIO_EUR,S13,GF01,D1,CH,NaN,NaN,NaN,NaN,...,6861.3,7115.7,8291.9,8225.9,8210.2,8090.4,8461.4,9067.8,9141.7,10268.9
4,A,MIO_EUR,S13,GF01,D1,CY,NaN,NaN,NaN,NaN,...,370.0,455.2,425.3,402.9,402.3,429.2,467.0,501.4,475.4,491.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1302116,A,PC_TOT,S1314,GF1009,TE,PT,NaN,NaN,NaN,NaN,...,1.4,1.4,1.2,1.1,1.2,1.5,1.1,1.2,1.2,1.2
1302117,A,PC_TOT,S1314,GF1009,TE,RO,NaN,NaN,NaN,NaN,...,0.9,1.1,1.2,0.9,2.0,1.5,1.8,1.7,1.9,1.7
1302118,A,PC_TOT,S1314,GF1009,TE,SE,NaN,NaN,NaN,NaN,...,0.1,0.2,0.2,0.1,0.1,0.1,0.1,0.2,0.2,0.1
1302119,A,PC_TOT,S1314,GF1009,TE,SI,NaN,NaN,NaN,NaN,...,0.2,0.2,0.1,0.1,0.1,0.2,0.1,0.1,0.1,0.1
1302120,A,PC_TOT,S1314,GF1009,TE,SK,NaN,NaN,NaN,NaN,...,1.4,1.7,1.5,1.7,1.9,1.8,2.0,1.8,1.5,1.5

In [38]:
for column in df.columns:
    print(f"Unikátne hodnoty v stĺpci {column}:")
    print(df[column].unique())
    print("\n")

Unikátne hodnoty v stĺpci freq:
['A']


Unikátne hodnoty v stĺpci unit:
['MIO_EUR' 'MIO_NAC' 'PC_GDP' 'PC_TOT']


Unikátne hodnoty v stĺpci sector:
['S13' 'S1311' 'S1312' 'S1313' 'S1314']


Unikátne hodnoty v stĺpci cofog99:
['GF01' 'GF0101' 'GF0102' 'GF0103' 'GF0104' 'GF0105' 'GF0106' 'GF0107'
 'GF0108' 'GF02' 'GF0201' 'GF0202' 'GF0203' 'GF0204' 'GF0205' 'GF03'
 'GF0301' 'GF0302' 'GF0303' 'GF0304' 'GF0305' 'GF0306' 'GF04' 'GF0401'
 'GF0402' 'GF0403' 'GF0404' 'GF0405' 'GF0406' 'GF0407' 'GF0408' 'GF0409'
 'GF05' 'GF0501' 'GF0502' 'GF0503' 'GF0504' 'GF0505' 'GF0506' 'GF06'
 'GF0601' 'GF0602' 'GF0603' 'GF0604' 'GF0605' 'GF0606' 'GF07' 'GF0701'
 'GF0702' 'GF0703' 'GF0704' 'GF0705' 'GF0706' 'GF08' 'GF0801' 'GF0802'
 'GF0803' 'GF0804' 'GF0805' 'GF0806' 'GF09' 'GF0901' 'GF0902' 'GF0903'
 'GF0904' 'GF0905' 'GF0906' 'GF0907' 'GF0908' 'GF10' 'GF1001' 'GF1002'
 'GF1003' 'GF1004' 'GF1005' 'GF1006' 'GF1007' 'GF1008' 'GF1009' 'TOTAL']


Unikátne hodnoty v stĺpci na_item:
['D1' 'D29_D5_D8' 'D3' 'D4' 'D4_S1311' 'D4_S1312' 'D4_S1313' 'D4_S1314'
 'D62' 'D62_D632' 'D632' 'D7' 'D7_S1311' 'D7_S1312' 'D7_S1313' 'D7_S1314'
 'D9' 'D92' 'D9_S1311' 'D9_S1312' 'D9_S1313' 'D9_S1314' 'NP' 'OP5ANP' 'P2'
 'P2_D29_D5_D8' 'P3' 'P31' 'P32' 'P5' 'P51G' 'TE']


Unikátne hodnoty v stĺpci geo\TIME_PERIOD:
['AT' 'BE' 'BG' 'CH' 'CY' 'CZ' 'DE' 'DK' 'EA19' 'EA20' 'EE' 'EL' 'ES'
 'EU27_2020' 'FI' 'FR' 'HR' 'HU' 'IE' 'IS' 'IT' 'LT' 'LU' 'LV' 'MT' 'NL'
 'NO' 'PL' 'PT' 'RO' 'SE' 'SI' 'SK']


Unikátne hodnoty v stĺpci 1990:
[         nan  1.81010e+03  7.30000e+00  1.96000e+01  1.53080e+03
  1.20000e+00  0.00000e+00  5.64600e+02  8.02200e+02  1.52720e+03
  1.53450e+03  2.22030e+03  6.26300e+03  7.53200e+02  3.70000e+00
  6.54000e+02  2.81700e+02  2.82900e+02  1.21490e+03  6.52700e+02
  6.16000e+02  1.69370e+03  1.02140e+03  2.08000e+01  1.39600e+02
  2.10600e+02  1.13530e+03  1.39250e+03  1.15850e+03  2.91350e+03
  8.60000e+00  1.89800e+02  2.51100e+02  2.11900e+02  5.76000e+01
  1.43650e+03  1.16340e+03  2.62570e+03  1.37900e+03  1.37530e+03
  7.12150e+03  9.67000e+01  6.10000e+00  1.47000e+01  6.12000e+01
  9.55000e+01  1.24900e+02  4.65000e+01  2.68200e+02  4.39700e+02
  3.06000e+01  1.00400e+02  2.20000e+01  3.67000e+01  1.27400e+02
  4.20100e+02  7.56800e+02  3.64830e+03  7.81300e+02  1.51900e+02
 -4.90000e+00  4.73900e+02  1.45980e+03  5.43260e+03  4.78800e+02
  6.51650e+03  5.68200e+02  3.55000e+01  2.97600e+02  3.46600e+02
  3.34300e+02  8.59700e+02  3.42900e+02  1.59700e+03  3.92260e+03
  2.82000e+01  3.11100e+02  4.06600e+02  2.67000e+02  2.57000e+01
  1.84000e+01  8.60900e+02  1.44390e+03  5.35300e+03  6.95490e+03
  2.73960e+03  1.59000e+01  1.56770e+04  1.59991e+04  3.22100e+02
  2.24100e+02  7.96000e+01  3.96800e+02  1.31410e+03  1.33000e+03
  3.86260e+03  3.17200e+02  2.07692e+04  1.61583e+04  2.45000e+01
  3.03350e+03  1.60077e+04  1.72066e+04  1.19900e+03  1.81740e+03
  3.95600e+02  3.49000e+02  1.53100e+02  5.20850e+03  7.95790e+03
  7.98240e+03  2.32492e+04  1.55080e+04  7.74110e+03  5.05540e+03
  5.01500e+03  5.33332e+04  8.63400e+02  1.01160e+03  3.24500e+02
 -2.69000e+01  4.43300e+02  6.61300e+02  1.38020e+03  4.70300e+02
  3.86140e+03  7.78900e+02  4.41000e+01  4.90000e+00  7.72000e+01
  1.71500e+02  9.00100e+02  1.07650e+03  9.25900e+02  2.75800e+03
  3.73500e+02  2.31500e+02  2.85300e+02  7.35000e+01  1.00910e+03
  6.56400e+02  1.86270e+03  9.62600e+02  6.05600e+03  6.98000e+01
  1.10000e+01  9.80000e+00  2.40000e+00  4.53000e+01  3.31000e+01
  1.05300e+02  3.43000e+01  1.75100e+02  8.45000e+01  1.06500e+02
  3.80000e+01  2.94000e+01  8.82000e+01  3.09800e+02  5.14000e+01
  4.11370e+03  4.06960e+03  1.49400e+02  1.48200e+02  6.00000e+01
  4.37700e+03  3.89400e+02  1.80000e+02  5.02000e+01  3.18000e+01
  5.74400e+02  9.85900e+02  2.71750e+03  2.47140e+03  1.38400e+02
  1.31000e+02  1.12700e+02  2.54700e+02  4.74680e+03  3.30170e+03
  3.32620e+03  1.66920e+03  1.46960e+03  1.83700e+02  1.04100e+02
  1.20000e+02  5.55140e+03  4.56800e+03  2.87800e+03  3.63240e+03
  3.65690e+03  1.02860e+04  7.42270e+03  1.47080e+03  1.09730e+03
  8.38900e+02  4.91100e+02  2.65510e+03  2.26070e+03  2.26930e+03
  6.95740e+03  1.40590e+03  2.62320e+03  2.58650e+03  2.84222e+04
  9.46700e+02  4.76400e+02  1.18800e+02  8.94000e+01  2.69000e+01
  3.58800e+02  8.23000e+02  7.89900e+02  3.31900e+02  2.72370e+03
  2.42500e+02  6.25000e+01  3.92000e+01  2.35100e+02  2.32700e+02
  1.55500e+02  1.22000e+01  4.27400e+02  5.07000e+02  7.63000e+02
  4.16400e+02  4.12700e+02  1.39000e+03  3.55200e+02  9.80000e+01
  4.72700e+02  3.59690e+03  9.31000e+01  1.43160e+03  4.68440e+03
  4.44600e+02  5.56490e+03  5.43800e+02  2.96400e+02  3.02500e+02
  8.25400e+02  2.92700e+02  1.23200e+03  2.93680e+03  4.16000e+01
  5.49900e+02  1.18920e+03  4.19450e+03  5.48700e+02  4.81300e+03
  2.41020e+03  1.03240e+03  1.32750e+03  2.95100e+02  4.36000e+02
  2.57200e+02  3.15840e+03  2.56000e+02  5.40200e+03  1.12915e+04
  1.51610e+03  4.83700e+02  1.22500e+02  4.29000e+01  2.42360e+03
  1.50022e+04  1.28627e+04  2.13950e+03  2.38080e+03  2.37710e+03
  2.20502e+04  5.88000e+01  1.09000e+02  6.88300e+02  7.92400e+02
  2.98800e+02  1.13429e+04  1.13454e+04  1.15100e+02  7.84000e+01
  1.29800e+02  2.93900e+02  5.51100e+02  1.21990e+04  1.20336e+04
  6.90700e+02  2.19200e+02  3.44100e+02  3.60100e+02  1.28960e+03
  1.23940e+03  1.31003e+04  1.47800e+03  6.00000e+00  1.60000e+01
  1.25000e+03  1.00000e+00  4.61000e+02  6.55000e+02  1.24700e+03
  1.25300e+03  1.81300e+03  5.11400e+03  6.15000e+02  3.00000e+00
  5.34000e+02  2.30000e+02  2.31000e+02  9.92000e+02  5.33000e+02
  5.03000e+02  1.38300e+03  8.34000e+02  1.70000e+01  1.14000e+02
  1.72000e+02  9.27000e+02  1.13700e+03  9.46000e+02  2.37900e+03
  7.00000e+00  1.55000e+02  2.05000e+02  1.73000e+02  4.70000e+01
  1.17300e+03  9.50000e+02  2.14400e+03  1.12600e+03  1.12300e+03
  5.81500e+03  7.90000e+01  5.00000e+00  1.20000e+01  5.00000e+01
  7.80000e+01  1.02000e+02  2.19000e+02  3.59000e+02  2.50000e+01
  8.20000e+01  1.80000e+01  3.00000e+01  1.04000e+02  3.43000e+02
  6.18000e+02  2.97900e+03  6.38000e+02  1.24000e+02 -4.00000e+00
  3.87000e+02  1.19200e+03  4.43600e+03  3.91000e+02  5.32100e+03
  4.64000e+02  2.90000e+01  2.43000e+02  2.83000e+02  2.73000e+02
  7.02000e+02  2.80000e+02  1.30400e+03  3.20300e+03  2.30000e+01
  2.54000e+02  3.32000e+02  2.18000e+02  2.10000e+01  1.50000e+01
  7.03000e+02  1.17900e+03  4.37100e+03  5.67900e+03  2.23700e+03
  1.30000e+01  1.28010e+04  1.30640e+04  2.63000e+02  1.83000e+02
  6.50000e+01  3.24000e+02  1.07300e+03  1.08600e+03  3.15400e+03
  2.59000e+02  1.69590e+04  2.00000e+01  2.47700e+03  1.30710e+04
  1.40500e+04  9.79000e+02  1.48400e+03  3.23000e+02  2.85000e+02
  1.25000e+02  4.25300e+03  6.49800e+03  6.51800e+03  1.89840e+04
  1.26630e+04  6.32100e+03  4.12800e+03  4.09500e+03  4.35490e+04
  7.05000e+02  8.26000e+02  2.65000e+02 -2.20000e+01  3.62000e+02
  5.40000e+02  1.12700e+03  3.84000e+02  3.15300e+03  6.36000e+02
  3.60000e+01  4.00000e+00  6.30000e+01  1.40000e+02  7.35000e+02
  8.79000e+02  7.56000e+02  2.25200e+03  3.05000e+02  1.89000e+02
  2.33000e+02  8.24000e+02  5.36000e+02  1.52100e+03  7.86000e+02
  4.94500e+03  5.70000e+01  9.00000e+00  8.00000e+00  2.00000e+00
  3.70000e+01  2.70000e+01  8.60000e+01  2.80000e+01  1.43000e+02
  6.90000e+01  8.70000e+01  3.10000e+01  2.40000e+01  7.20000e+01
  2.53000e+02  4.20000e+01  3.35900e+03  3.32300e+03  1.22000e+02
  1.21000e+02  4.90000e+01  3.57400e+03  3.18000e+02  1.47000e+02
  4.10000e+01  2.60000e+01  4.69000e+02  8.05000e+02  2.21900e+03
  2.01800e+03  1.13000e+02  1.07000e+02  9.20000e+01  2.08000e+02
  3.87600e+03  2.69600e+03  2.71600e+03  1.36300e+03  1.20000e+03
  1.50000e+02  8.50000e+01  4.53300e+03  3.73000e+03  2.35000e+03
  2.96600e+03  2.98600e+03  8.39900e+03  6.06100e+03  1.20100e+03
  8.96000e+02  6.85000e+02  4.01000e+02  2.16800e+03  1.84600e+03
  1.85300e+03  5.68100e+03  1.14800e+03  2.14200e+03  2.11200e+03
  2.32080e+04  7.73000e+02  3.89000e+02  9.70000e+01  7.30000e+01
  2.93000e+02  6.72000e+02  6.45000e+02  2.71000e+02  2.22400e+03
  1.98000e+02  5.10000e+01  3.20000e+01  1.92000e+02  1.90000e+02
  1.27000e+02  1.00000e+01  4.14000e+02  6.23000e+02  3.40000e+02
  3.37000e+02  1.13500e+03  2.90000e+02  8.00000e+01  3.86000e+02
  2.93700e+03  7.60000e+01  1.16900e+03  3.82500e+03  3.63000e+02
  4.54400e+03  4.44000e+02  2.42000e+02  2.47000e+02  6.74000e+02
  2.39000e+02  1.00600e+03  2.39800e+03  3.40000e+01  4.49000e+02
  9.71000e+02  3.42500e+03  4.48000e+02  3.93000e+03  1.96800e+03
  8.43000e+02  1.08400e+03  2.41000e+02  3.56000e+02  2.10000e+02
  2.57900e+03  2.09000e+02  4.41100e+03  9.22000e+03  1.23800e+03
  3.95000e+02  1.00000e+02  3.50000e+01  1.97900e+03  1.22500e+04
  1.05030e+04  1.74700e+03  1.94400e+03  1.94100e+03  1.80050e+04
  4.80000e+01  8.90000e+01  5.62000e+02  6.47000e+02  2.44000e+02
  9.26200e+03  9.26400e+03  9.40000e+01  6.40000e+01  1.06000e+02
  2.40000e+02  4.50000e+02  9.96100e+03  9.82600e+03  5.64000e+02
  1.79000e+02  2.81000e+02  2.94000e+02  1.05300e+03  1.01200e+03
  1.06970e+04  1.60000e+00  1.40000e+00  5.00000e-01  7.00000e-01
  5.60000e+00  6.00000e-01  3.00000e-01  1.10000e+00  1.50000e+00
  9.00000e-01  1.00000e-01  2.00000e-01  1.30000e+00  2.60000e+00
  6.40000e+00  4.00000e-01  3.30000e+00  5.80000e+00  8.00000e-01
  3.50000e+00  4.80000e+00  6.20000e+00  2.50000e+00  1.41000e+01
  1.44000e+01  1.86000e+01  1.45000e+01  2.70000e+00  1.54000e+01
  4.70000e+00  7.10000e+00  7.20000e+00  2.09000e+01  1.39000e+01
  6.90000e+00  4.50000e+00  4.79000e+01  1.70000e+00  5.40000e+00
  3.90000e+00  2.20000e+00  4.30000e+00  4.10000e+00  9.20000e+00
  6.70000e+00  2.30000e+00  2.55000e+01  3.20000e+00  4.20000e+00
  3.80000e+00  2.80000e+00  1.01000e+01  1.35000e+01  1.15000e+01
  1.90000e+00  2.10000e+00  1.98000e+01  1.02000e+01  1.08000e+01
  1.18000e+01  1.12000e+01  3.11000e+01  1.92000e+01  9.60000e+00
  2.87000e+01  1.17000e+01  1.26000e+01  5.20000e+00  1.57000e+01
  1.29000e+01  1.23000e+01  6.30000e+00  9.60000e+01  1.04000e+01
  6.35000e+01  6.07000e+01  3.76000e+01  2.76000e+01  1.46000e+01
  1.13000e+01  3.39000e+01  2.73000e+01  2.74000e+01  1.34000e+01
  5.50000e+00  1.80000e+00  2.26000e+01  6.52000e+01  8.40000e+00
 -3.20000e+00  9.10000e+00  1.83000e+01  2.34000e+01  9.50000e+00
  1.64000e+01  6.80000e+00  2.43000e+01  6.50000e+00  5.30000e+00
  1.65000e+01  1.81000e+01  3.45000e+01  1.71000e+01  9.79000e+01
  9.30000e+01  2.01000e+01  2.28000e+01  5.20000e+01  7.60000e+00
  1.67000e+01  1.66000e+01  2.49000e+01  3.89000e+01  1.89000e+01
  8.57000e+01  4.40000e+00 -8.46000e+01  2.89000e+01  2.91000e+01
  1.79000e+01  1.82000e+01  1.36000e+01  1.43000e+01  2.46000e+01
  1.25000e+01  1.75000e+01  2.19000e+01  2.38000e+01  2.90000e+00
  1.62000e+01  2.03000e+01  9.58000e+01  3.60000e+00  3.10000e+00
  2.96000e+01  1.46200e+02  2.68000e+01  3.36000e+01  3.72000e+01
  2.13000e+01  3.46000e+01  4.00000e+01  5.48000e+01  1.78000e+01
  3.02000e+01  2.16000e+01  8.50000e+00  2.64000e+01  3.33000e+01
  1.56000e+01  2.29000e+01  8.24000e+01  1.19000e+01  9.09000e+01
  9.10000e+01  9.99000e+01  2.12000e+01  1.09000e+01  1.95000e+01
  6.29000e+01  1.48000e+01  3.69000e+01  1.40000e+01  1.24000e+01
  1.76000e+01  5.10000e+00  3.57000e+01  1.74000e+01  1.55000e+01
  3.19000e+01 -1.14000e+01  2.67000e+01  3.12000e+01  3.64000e+01
  1.87000e+01  2.52000e+01  1.07000e+01  5.70000e+00  1.97000e+01
  2.27000e+01  2.22000e+01  3.26000e+01  2.31000e+01  2.18000e+01
  8.76000e+01  6.10000e+01  6.14000e+01  1.06000e+01  1.68000e+01
  2.11000e+01  9.96000e+01  4.75000e+01  5.34000e+01  5.55000e+01
  9.43000e+01  5.25000e+01  8.54000e+01  8.61000e+01  4.27000e+01
  4.45000e+01]


Unikátne hodnoty v stĺpci 1991:
[         nan  1.94820e+03  7.10000e+00  1.43000e+01  1.90180e+03
  4.80000e+00  0.00000e+00  6.53800e+02  5.94000e+01 -1.20000e+00
  8.17800e+02  1.54760e+03  1.55470e+03  2.17400e+03  8.19000e+02
  6.95480e+03  8.53400e+02  1.20000e+00  3.60000e+00  6.89400e+02
  3.16200e+02  3.17400e+02  1.41920e+03  6.88200e+02  6.13300e+02
  1.86380e+03  1.12450e+03  2.26000e+01  1.49800e+02  2.19900e+02
  1.23380e+03  1.51790e+03  1.24330e+03  3.18320e+03  1.72400e+02
  3.51800e+02  2.02100e+02  2.85000e+01  1.43230e+03  1.23740e+03
  2.81230e+03  1.40380e+03  1.39780e+03  7.62520e+03  1.15300e+02
  5.90000e+00  1.31000e+01  6.42000e+01  1.02200e+02  5.11000e+01
  3.05500e+02  4.63600e+02  1.16500e+02  1.90000e+01  3.68000e+01
  1.34300e+02  4.41000e+02  7.98800e+02  3.93200e+03  8.57000e+02
  1.80700e+02  9.50000e+00 -4.80000e+00  4.30300e+02  1.51200e+03
  5.79580e+03  4.35000e+02  6.92150e+03  6.06200e+02  4.28000e+01
  2.38900e+02  1.07000e+01  3.18600e+02  3.37600e+02  9.01000e+02
  3.15000e+02  1.56190e+03  4.12820e+03  3.09000e+01  3.93400e+02
  4.93300e+02  9.98000e+01  2.99500e+02  1.66000e+01  8.28500e+02
  1.60940e+03  5.59020e+03  8.27300e+02  7.41830e+03  2.97640e+03
  1.81280e+04  1.84632e+04  3.35200e+02  3.19700e+02  9.03000e+01
  3.45000e+01  2.88800e+02  1.42280e+03  1.43590e+03  4.18280e+03
  2.54400e+02  2.35756e+04  1.73911e+04  2.14000e+01  3.30560e+03
  1.90300e+03  1.85381e+04  1.98302e+04  1.29210e+03  2.00760e+03
  5.88400e+02  3.66100e+02  7.61000e+01  5.05650e+03  8.43940e+03
  8.46080e+03  2.47000e+04  1.64699e+04  8.23020e+03  4.98040e+03
  4.89960e+03  5.85431e+04  9.39000e+02  1.27420e+03  1.00680e+03
  3.81600e+02  5.08700e+02  6.52600e+02  6.59700e+02  1.40740e+03
  4.46690e+03  8.70100e+02  3.57000e+01  1.55000e+01  2.40000e+00
  7.73000e+01  1.75900e+02  9.96100e+02  1.16250e+03  9.97300e+02
  3.02870e+03  4.17200e+02  2.92400e+02  4.04100e+02  5.23000e+01
  2.02000e+01  1.03770e+03  7.31000e+02  2.02550e+03  1.01750e+03
  6.62080e+03  8.44000e+01  1.19000e+01  1.78000e+01  4.04000e+01
  1.21200e+02  2.00900e+02  8.68000e+01  1.23600e+02  2.38000e+01
  3.33000e+01  9.63000e+01  3.26900e+02  4.75000e+01  4.47760e+03
  4.40040e+03  1.39100e+02  1.29600e+02  2.73000e+01  4.73200e+03
  2.97000e+01  3.38800e+02  1.89000e+02  3.80000e+01  4.87000e+01
  5.57500e+02  1.09240e+03  2.76720e+03  2.48900e+03  1.64000e+02
  1.52100e+02  1.35500e+02  3.72000e+02  3.85100e+02  1.33600e+03
  5.20510e+03  3.59800e+03  3.62420e+03  2.62000e+01  3.19750e+03
  1.26000e+02  2.93600e+03  8.14200e+02  1.92600e+02  6.21700e+02
  1.41400e+02  7.82720e+03  5.04100e+03  8.30000e+00  3.15110e+03
  4.00810e+03  4.03430e+03  1.23797e+04  7.91760e+03  1.67480e+03
  8.30900e+02  4.65900e+02  2.86340e+03  2.53660e+03  2.54490e+03
  7.69050e+03  1.62490e+03  6.06570e+03  2.83250e+03  2.75770e+03
  3.29635e+04  1.00920e+03  5.93100e+02  1.07000e+02  3.09000e+02
  8.46300e+02  7.17900e+02  3.10200e+02  2.89320e+03  7.25000e+01
  4.40000e+01  2.37700e+02  3.73200e+02  2.46000e+02  1.54500e+02
  2.50000e+01  3.94600e+02  5.06400e+02  7.86900e+02  3.86300e+02
  3.80400e+02  1.38240e+03  6.66000e+01  3.76800e+02  1.01000e+02
  3.44700e+02  4.95700e+02  3.88450e+03  9.75000e+01  3.89900e+02
  1.48460e+03  4.98520e+03  5.86000e+03  5.76500e+02  8.91000e+01
  8.52300e+02  2.50800e+02  1.22070e+03  3.03580e+03  4.56400e+02
  1.22430e+03  4.25420e+03  4.55300e+02  4.86870e+03  2.61380e+03
  1.17440e+03  1.48110e+03  3.06700e+02  5.15900e+02  4.44600e+02
  2.08000e+02  9.33100e+02  3.39600e+03  5.75190e+03  1.20279e+04
  1.67840e+03  5.04000e+02  8.74800e+02  1.61700e+02  2.12170e+03
  5.50580e+03  1.56033e+04  1.34876e+04  2.11580e+03  2.11100e+03
  2.10510e+03  2.29670e+04  7.59500e+02  8.59400e+02  3.22100e+02
  1.33556e+04  1.33580e+04  1.13040e+03  9.79400e+02  7.13000e+01
  3.48300e+02  3.61300e+02  5.97900e+02  1.52444e+04  1.41175e+04
  7.61900e+02  1.23020e+03  3.97000e+02  4.10100e+02  1.40620e+03
  1.35740e+03  1.62036e+04  1.63900e+03  6.00000e+00  1.20000e+01
  1.60000e+03  4.00000e+00  5.50000e+02  5.00000e+01 -1.00000e+00
  6.88000e+02  1.30200e+03  1.30800e+03  1.82900e+03  6.89000e+02
  5.85100e+03  7.18000e+02  1.00000e+00  3.00000e+00  5.80000e+02
  2.66000e+02  2.67000e+02  1.19400e+03  5.79000e+02  5.16000e+02
  1.56800e+03  9.46000e+02  1.85000e+02  1.03800e+03  1.27700e+03
  1.04600e+03  2.67800e+03  1.45000e+02  2.96000e+02  1.70000e+02
  2.40000e+01  1.20500e+03  1.04100e+03  2.36600e+03  1.18100e+03
  1.17600e+03  6.41500e+03  9.70000e+01  5.00000e+00  1.10000e+01
  5.40000e+01  8.60000e+01  4.30000e+01  2.57000e+02  3.90000e+02
  9.80000e+01  1.60000e+01  3.10000e+01  1.13000e+02  3.71000e+02
  6.72000e+02  3.30800e+03  7.21000e+02  1.52000e+02  8.00000e+00
 -4.00000e+00  3.62000e+02  1.27200e+03  4.87600e+03  3.66000e+02
  5.82300e+03  5.10000e+02  3.60000e+01  2.01000e+02  9.00000e+00
  2.68000e+02  2.84000e+02  7.58000e+02  2.65000e+02  1.31400e+03
  3.47300e+03  2.60000e+01  3.31000e+02  4.15000e+02  8.40000e+01
  2.52000e+02  1.40000e+01  6.97000e+02  1.35400e+03  4.70300e+03
  6.96000e+02  6.24100e+03  2.50400e+03  1.52510e+04  1.55330e+04
  2.82000e+02  2.69000e+02  7.60000e+01  2.90000e+01  2.43000e+02
  1.19700e+03  1.20800e+03  3.51900e+03  2.14000e+02  1.98340e+04
  1.46310e+04  1.80000e+01  2.78100e+03  1.60100e+03  1.55960e+04
  1.66830e+04  1.08700e+03  1.68900e+03  4.95000e+02  3.08000e+02
  6.40000e+01  4.25400e+03  7.10000e+03  7.11800e+03  2.07800e+04
  1.38560e+04  6.92400e+03  4.19000e+03  4.12200e+03  4.92520e+04
  7.90000e+02  1.07200e+03  8.47000e+02  3.21000e+02  4.28000e+02
  5.49000e+02  5.55000e+02  1.18400e+03  3.75800e+03  7.32000e+02
  3.00000e+01  1.30000e+01  2.00000e+00  6.50000e+01  1.48000e+02
  8.38000e+02  9.78000e+02  8.39000e+02  2.54800e+03  3.51000e+02
  3.40000e+02  1.70000e+01  8.73000e+02  6.15000e+02  1.70400e+03
  8.56000e+02  5.57000e+03  7.10000e+01  1.00000e+01  1.50000e+01
  3.40000e+01  1.02000e+02  1.69000e+02  7.30000e+01  1.04000e+02
  2.00000e+01  2.80000e+01  8.10000e+01  2.75000e+02  4.00000e+01
  3.76700e+03  3.70200e+03  1.17000e+02  1.09000e+02  2.30000e+01
  3.98100e+03  2.85000e+02  1.59000e+02  3.20000e+01  4.10000e+01
  4.69000e+02  9.19000e+02  2.32800e+03  2.09400e+03  1.38000e+02
  1.28000e+02  1.14000e+02  3.13000e+02  3.24000e+02  1.12400e+03
  4.37900e+03  3.02700e+03  3.04900e+03  2.20000e+01  2.69000e+03
  1.06000e+02  2.47000e+03  6.85000e+02  1.62000e+02  5.23000e+02
  1.19000e+02  6.58500e+03  4.24100e+03  7.00000e+00  2.65100e+03
  3.37200e+03  3.39400e+03  1.04150e+04  6.66100e+03  1.40900e+03
  6.99000e+02  3.92000e+02  2.40900e+03  2.13400e+03  2.14100e+03
  6.47000e+03  1.36700e+03  5.10300e+03  2.38300e+03  2.32000e+03
  2.77320e+04  8.49000e+02  4.99000e+02  9.00000e+01  2.60000e+02
  7.12000e+02  6.04000e+02  2.61000e+02  2.43400e+03  6.10000e+01
  3.70000e+01  2.00000e+02  3.14000e+02  2.07000e+02  1.30000e+02
  2.10000e+01  3.32000e+02  4.26000e+02  6.62000e+02  3.25000e+02
  3.20000e+02  1.16300e+03  5.60000e+01  3.17000e+02  8.50000e+01
  2.90000e+02  4.17000e+02  3.26800e+03  8.20000e+01  3.28000e+02
  1.24900e+03  4.19400e+03  4.93000e+03  4.85000e+02  7.50000e+01
  7.17000e+02  2.11000e+02  1.02700e+03  2.55400e+03  3.84000e+02
  1.03000e+03  3.57900e+03  3.83000e+02  4.09600e+03  2.19900e+03
  9.88000e+02  1.24600e+03  2.58000e+02  4.34000e+02  3.74000e+02
  1.75000e+02  7.85000e+02  2.85700e+03  4.83900e+03  1.01190e+04
  1.41200e+03  4.24000e+02  7.36000e+02  1.36000e+02  1.78500e+03
  4.63200e+03  1.31270e+04  1.13470e+04  1.78000e+03  1.77600e+03
  1.77100e+03  1.93220e+04  6.39000e+02  7.23000e+02  2.71000e+02
  1.12360e+04  1.12380e+04  9.51000e+02  8.24000e+02  6.00000e+01
  2.93000e+02  3.04000e+02  5.03000e+02  1.28250e+04  1.18770e+04
  6.41000e+02  1.03500e+03  3.34000e+02  3.45000e+02  1.18300e+03
  1.14200e+03  1.36320e+04  1.90000e+00  1.80000e+00  6.00000e-01
  1.00000e-01  8.00000e-01  1.50000e+00  2.10000e+00  6.70000e+00
  7.00000e-01  3.00000e-01  1.40000e+00  1.10000e+00  2.00000e-01
  3.10000e+00  2.70000e+00  7.40000e+00  4.00000e-01  3.80000e+00
  5.60000e+00  9.00000e-01  5.00000e-01  1.60000e+00  5.40000e+00

In [39]:
#CHYBA!!!!! nemôžem ho odstrániť, musím si najprv len vyfiltrovať to kde je total
import pandas as pd
# odstránim stlpec cofog99, ktorý nám netreba
#df = df.drop(columns=['cofog99'])
#df

# Filtrovanie riadkov, kde v 'unit' nie je 'MIO_NAC'
df = df[df['cofog99'] == 'TOTAL']

# Zobrazenie výsledkov
df

#až teraz môžem odstrániť
df = df.drop(columns=['cofog99'])
df

,freq,unit,sector,na_item,geo\TIME_PERIOD,1990,1991,1992,1993,1994,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
82634,A,MIO_EUR,S13,D1,AT,NaN,NaN,NaN,NaN,NaN,...,34631.5,35359.1,36768.3,37991.2,39108.6,40363.4,41843.9,43163.6,44828.3,46501.1
82635,A,MIO_EUR,S13,D1,BE,NaN,NaN,NaN,NaN,NaN,...,50694.4,52173.6,52330.0,53619.7,55310.0,56871.4,58768.1,60486.7,62691.2,68025.3
82636,A,MIO_EUR,S13,D1,BG,NaN,NaN,NaN,NaN,NaN,...,3975.8,4072.1,4268.3,4341.2,4798.3,5327.5,6140.9,6642.0,7882.0,8654.3
82637,A,MIO_EUR,S13,D1,CH,NaN,NaN,NaN,NaN,NaN,...,38898.3,40103.8,46401.5,46011.1,45820.9,44715.3,47352.7,50531.0,51343.5,56484.6
82638,A,MIO_EUR,S13,D1,CY,NaN,NaN,NaN,NaN,NaN,...,2596.4,2343.1,2281.9,2270.3,2365.0,2484.2,2737.7,2900.9,2997.6,3179.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266118,A,PC_TOT,S1313,P3,MT,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1266119,A,PC_TOT,S1313,P31,MT,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN
1266120,A,PC_TOT,S1313,P32,MT,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1266121,A,PC_TOT,S1313,P5,MT,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1266122,A,PC_TOT,S1313,P51G,MT,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0

In [40]:
#chcem zistiť, čo ešte môžem vymazať - zobrazím si unikátne hodnoty v každom stlpci a zisťujem, že vo freq je len 1 - mažem stlpec
print(df.nunique())

# Zobrazenie konkrétnych unikátnych hodnôt pre každý stĺpec
for column in df.columns:
    print(f"Unikátne hodnoty v stĺpci {column}:")
    print(df[column].unique())
    print("\n")

freq                  1
unit                  4
sector                5
na_item              32
geo\TIME_PERIOD      33
1990                208
1991                211
1992                206
1993                205
1994                206
1995               3958
1996               4047
1997               4059
1998               4248
1999               3413
2000               3444
2001               3410
2002               3456
2003               3438
2004               3491
2005               3501
2006               3487
2007               3449
2008               3418
2009               3395
2010               3398
2011               3382
2012               3456
2013               3448
2014               3394
2015               3417
2016               3394
2017               3441
2018               3438
2019               3422
2020               3452
2021               3466
2022               3458
dtype: int64
Unikátne hodnoty v stĺpci freq:
['A']


Unikátne hodnoty v stĺpci unit:
['MIO_EUR' 'MIO_NAC' 'PC_GDP' 'PC_TOT']


Unikátne hodnoty v stĺpci sector:
['S13' 'S1311' 'S1312' 'S1313' 'S1314']


Unikátne hodnoty v stĺpci na_item:
['D1' 'D29_D5_D8' 'D3' 'D4' 'D4_S1311' 'D4_S1312' 'D4_S1313' 'D4_S1314'
 'D62' 'D62_D632' 'D632' 'D7' 'D7_S1311' 'D7_S1312' 'D7_S1313' 'D7_S1314'
 'D9' 'D92' 'D9_S1311' 'D9_S1312' 'D9_S1313' 'D9_S1314' 'NP' 'OP5ANP' 'P2'
 'P2_D29_D5_D8' 'P3' 'P31' 'P32' 'P5' 'P51G' 'TE']


Unikátne hodnoty v stĺpci geo\TIME_PERIOD:
['AT' 'BE' 'BG' 'CH' 'CY' 'CZ' 'DE' 'DK' 'EA19' 'EA20' 'EE' 'EL' 'ES'
 'EU27_2020' 'FI' 'FR' 'HR' 'HU' 'IE' 'IS' 'IT' 'LT' 'LU' 'LV' 'MT' 'NL'
 'NO' 'PL' 'PT' 'RO' 'SE' 'SI' 'SK']


Unikátne hodnoty v stĺpci 1990:
[        nan 1.61583e+04 2.45000e+01 3.03350e+03 1.53080e+03 1.60077e+04
 1.72066e+04 1.19900e+03 1.81740e+03 3.95600e+02 3.49000e+02 1.53100e+02
 5.20850e+03 7.95790e+03 7.98240e+03 2.32492e+04 1.55080e+04 7.74110e+03
 5.05540e+03 5.01500e+03 5.33332e+04 4.56800e+03 8.60000e+00 2.87800e+03
 1.01160e+03 0.00000e+00 3.63240e+03 3.65690e+03 1.02860e+04 7.42270e+03
 1.47080e+03 1.09730e+03 8.38900e+02 4.91100e+02 2.11900e+02 3.18000e+01
 2.65510e+03 2.26070e+03 2.26930e+03 6.95740e+03 1.40590e+03 5.55140e+03
 2.62320e+03 2.58650e+03 2.84222e+04 1.12915e+04 1.55500e+02 4.76400e+02
 1.59000e+01 1.03240e+03 1.51610e+03 4.83700e+02 8.25400e+02 1.22500e+02
 4.36000e+02 7.30000e+00 4.29000e+01 2.42360e+03 5.35300e+03 1.50022e+04
 1.28627e+04 2.13950e+03 2.38080e+03 2.37710e+03 2.20502e+04 2.98800e+02
 5.88000e+01 1.13429e+04 1.20336e+04 6.90700e+02 2.19200e+02 2.20000e+01
 3.92000e+01 7.84000e+01 1.29800e+02 3.44100e+02 3.60100e+02 1.28960e+03
 1.23940e+03 5.02000e+01 5.14000e+01 1.31003e+04 2.00000e+01 2.47700e+03
 1.25000e+03 1.30710e+04 1.40500e+04 9.79000e+02 1.48400e+03 3.23000e+02
 2.85000e+02 1.25000e+02 4.25300e+03 6.49800e+03 6.51800e+03 1.89840e+04
 1.26630e+04 6.32100e+03 4.12800e+03 4.09500e+03 4.35490e+04 3.73000e+03
 7.00000e+00 2.35000e+03 8.26000e+02 2.96600e+03 2.98600e+03 8.39900e+03
 6.06100e+03 1.20100e+03 8.96000e+02 6.85000e+02 4.01000e+02 1.73000e+02
 2.60000e+01 2.16800e+03 1.84600e+03 1.85300e+03 5.68100e+03 1.14800e+03
 4.53300e+03 2.14200e+03 2.11200e+03 2.32080e+04 9.22000e+03 1.27000e+02
 3.89000e+02 1.30000e+01 8.43000e+02 1.23800e+03 3.95000e+02 6.74000e+02
 1.00000e+02 3.56000e+02 6.00000e+00 3.50000e+01 1.97900e+03 4.37100e+03
 1.22500e+04 1.05030e+04 1.74700e+03 1.94400e+03 1.94100e+03 1.80050e+04
 2.44000e+02 4.80000e+01 9.26200e+03 9.82600e+03 5.64000e+02 1.79000e+02
 1.80000e+01 3.20000e+01 6.40000e+01 1.06000e+02 2.81000e+02 2.94000e+02
 1.05300e+03 1.01200e+03 4.10000e+01 4.20000e+01 1.06970e+04 1.45000e+01
 2.70000e+00 1.40000e+00 1.44000e+01 1.54000e+01 1.10000e+00 1.60000e+00
 4.00000e-01 3.00000e-01 1.00000e-01 4.70000e+00 7.10000e+00 7.20000e+00
 2.09000e+01 1.39000e+01 6.90000e+00 4.50000e+00 4.79000e+01 4.10000e+00
 2.60000e+00 9.00000e-01 3.30000e+00 9.20000e+00 6.70000e+00 1.30000e+00
 1.00000e+00 8.00000e-01 2.00000e-01 2.40000e+00 2.00000e+00 6.20000e+00
 5.00000e+00 2.30000e+00 2.55000e+01 1.01000e+01 7.00000e-01 2.20000e+00
 4.80000e+00 1.35000e+01 1.15000e+01 1.90000e+00 2.10000e+00 1.98000e+01
 1.02000e+01 1.08000e+01 6.00000e-01 1.20000e+00 1.18000e+01]


Unikátne hodnoty v stĺpci 1991:
[        nan 1.73911e+04 2.14000e+01 3.30560e+03 1.90300e+03 1.85381e+04
 1.98302e+04 1.29210e+03 2.00760e+03 5.88400e+02 3.66100e+02 7.61000e+01
 5.05650e+03 8.43940e+03 8.46080e+03 2.47000e+04 1.64699e+04 8.23020e+03
 4.98040e+03 4.89960e+03 5.85431e+04 5.04100e+03 8.30000e+00 3.15110e+03
 1.27420e+03 0.00000e+00 4.00810e+03 4.03430e+03 2.62000e+01 1.23797e+04
 7.91760e+03 2.93600e+03 1.67480e+03 8.30900e+02 4.65900e+02 6.21700e+02
 3.09000e+01 2.86340e+03 2.53660e+03 2.54490e+03 7.69050e+03 1.62490e+03
 6.06570e+03 2.83250e+03 2.75770e+03 3.29635e+04 1.20279e+04 1.54500e+02
 5.93100e+02 1.66000e+01 1.17440e+03 1.67840e+03 5.04000e+02 8.74800e+02
 1.61700e+02 4.44600e+02 1.07000e+01 9.50000e+00 2.12170e+03 5.50580e+03
 1.56033e+04 1.34876e+04 2.11580e+03 2.11100e+03 2.10510e+03 2.29670e+04
 3.22100e+02 1.31000e+01 5.23000e+01 1.33556e+04 1.41175e+04 7.61900e+02
 1.23020e+03 9.79400e+02 3.80000e+01 3.45000e+01 7.13000e+01 3.97000e+02
 4.10100e+02 1.40620e+03 1.35740e+03 4.87000e+01 3.68000e+01 1.62036e+04
 1.46310e+04 1.80000e+01 2.78100e+03 1.60100e+03 1.55960e+04 1.66830e+04
 1.08700e+03 1.68900e+03 4.95000e+02 3.08000e+02 6.40000e+01 4.25400e+03
 7.10000e+03 7.11800e+03 2.07800e+04 1.38560e+04 6.92400e+03 4.19000e+03
 4.12200e+03 4.92520e+04 4.24100e+03 7.00000e+00 2.65100e+03 1.07200e+03
 3.37200e+03 3.39400e+03 2.20000e+01 1.04150e+04 6.66100e+03 2.47000e+03
 1.40900e+03 6.99000e+02 3.92000e+02 5.23000e+02 2.60000e+01 2.40900e+03
 2.13400e+03 2.14100e+03 6.47000e+03 1.36700e+03 5.10300e+03 2.38300e+03
 2.32000e+03 2.77320e+04 1.01190e+04 1.30000e+02 4.99000e+02 1.40000e+01
 9.88000e+02 1.41200e+03 4.24000e+02 7.36000e+02 1.36000e+02 3.74000e+02
 9.00000e+00 8.00000e+00 1.78500e+03 4.63200e+03 1.31270e+04 1.13470e+04
 1.78000e+03 1.77600e+03 1.77100e+03 1.93220e+04 2.71000e+02 1.10000e+01
 4.40000e+01 1.12360e+04 1.18770e+04 6.41000e+02 1.03500e+03 8.24000e+02
 3.20000e+01 2.90000e+01 6.00000e+01 3.34000e+02 3.45000e+02 1.18300e+03
 1.14200e+03 4.10000e+01 3.10000e+01 1.36320e+04 1.68000e+01 3.20000e+00
 1.80000e+00 1.79000e+01 1.92000e+01 1.30000e+00 1.90000e+00 6.00000e-01
 4.00000e-01 1.00000e-01 4.90000e+00 8.20000e+00 2.39000e+01 1.59000e+01
 4.80000e+00 4.70000e+00 5.67000e+01 3.10000e+00 1.20000e+00 3.90000e+00
 1.20000e+01 7.70000e+00 2.80000e+00 1.60000e+00 8.00000e-01 5.00000e-01
 2.50000e+00 7.40000e+00 5.90000e+00 2.70000e+00 3.19000e+01 1.16000e+01
 1.10000e+00 2.00000e-01 2.10000e+00 5.30000e+00 1.51000e+01 2.00000e+00
 2.22000e+01 3.00000e-01 1.29000e+01 1.37000e+01 7.00000e-01 9.00000e-01
 1.40000e+00 1.57000e+01]


Unikátne hodnoty v stĺpci 1992:
[         nan  1.50071e+04  1.23000e+01  2.87810e+03  2.15220e+03
  1.87965e+04  1.99012e+04  1.10480e+03  1.79380e+03  4.46400e+02
  3.18400e+02  2.97000e+01  4.20510e+03  7.25320e+03  7.26550e+03
  2.10685e+04  1.40528e+04  7.01570e+03  4.17540e+03  4.15900e+03
  5.36495e+04  4.40070e+03  3.10000e+00  2.73890e+03  1.49590e+03
  0.00000e+00  3.97160e+03  3.99620e+03  2.46000e+01  1.11716e+04
  6.94300e+03  2.92630e+03  1.10270e+03  6.92100e+02  3.74700e+02
  2.82600e+02  3.69000e+01  2.65290e+03  2.27610e+03  2.27920e+03
  6.74740e+03  1.41500e+03  5.33240e+03  2.61600e+03  2.59350e+03
  2.98380e+04  1.03279e+04  1.39200e+02  6.12300e+02  1.74000e+01
  1.16620e+03  1.59730e+03  4.31100e+02  9.46100e+02  1.52600e+02
  5.76400e+02  9.20000e+00  8.20000e+00 -7.20000e+00  1.44470e+03
  4.63610e+03  1.31354e+04  1.14900e+04  1.64540e+03  1.45190e+03
  1.45800e+03  1.97128e+04  2.78500e+02  6.14000e+01  1.36586e+04
  1.43078e+04  6.49100e+02  1.33000e+03  1.02290e+03  3.28000e+01
  1.07500e+02  3.41000e+02  3.50200e+02  1.18570e+03  1.14780e+03
  3.79000e+01  1.64354e+04  1.46570e+04  1.20000e+01  2.81100e+03
  2.10200e+03  1.83580e+04  1.94370e+04  1.07900e+03  1.75200e+03
  4.36000e+02  3.11000e+02  2.90000e+01  4.10700e+03  7.08400e+03
  7.09600e+03  2.05770e+04  1.37250e+04  6.85200e+03  4.07800e+03
  4.06200e+03  5.23980e+04  4.29800e+03  3.00000e+00  2.67500e+03
  1.46100e+03  3.87900e+03  3.90300e+03  2.40000e+01  1.09110e+04
  6.78100e+03  2.85800e+03  1.07700e+03  6.76000e+02  3.66000e+02
  2.76000e+02  3.60000e+01  2.59100e+03  2.22300e+03  2.22600e+03
  6.59000e+03  1.38200e+03  5.20800e+03  2.55500e+03  2.53300e+03
  2.91420e+04  1.00870e+04  1.36000e+02  5.98000e+02  1.70000e+01
  1.13900e+03  1.56000e+03  4.21000e+02  9.24000e+02  1.49000e+02
  5.63000e+02  9.00000e+00  8.00000e+00 -7.00000e+00  1.41100e+03
  4.52800e+03  1.28290e+04  1.12220e+04  1.60700e+03  1.41800e+03
  1.42400e+03  1.92530e+04  2.72000e+02  6.00000e+01  1.33400e+04
  1.39740e+04  6.34000e+02  1.29900e+03  9.99000e+02  3.20000e+01
  1.05000e+02  3.33000e+02  3.42000e+02  1.15800e+03  1.12100e+03
  3.70000e+01  1.60520e+04  1.73000e+01  3.30000e+00  2.50000e+00
  2.17000e+01  2.29000e+01  1.30000e+00  2.10000e+00  5.00000e-01
  4.00000e-01  4.80000e+00  8.40000e+00  2.43000e+01  1.62000e+01
  8.10000e+00  6.18000e+01  5.10000e+00  3.20000e+00  1.70000e+00
  4.60000e+00  1.29000e+01  3.40000e+00  8.00000e-01  3.00000e-01
  2.60000e+00  7.80000e+00  1.60000e+00  6.10000e+00  3.44000e+01
  1.19000e+01  2.00000e-01  7.00000e-01  1.80000e+00  1.10000e+00
  5.30000e+00  1.51000e+01  1.32000e+01  1.90000e+00  2.27000e+01
  1.00000e-01  1.57000e+01  1.65000e+01  1.50000e+00  1.20000e+00
  1.40000e+00  1.89000e+01]


Unikátne hodnoty v stĺpci 1993:
[        nan 1.22763e+04 2.31000e+01 2.38050e+03 3.28170e+03 1.75914e+04
 1.85619e+04 9.70500e+02 1.62670e+03 1.24400e+03 2.22000e+02 9.80000e+00
 3.11660e+03 6.31750e+03 6.34060e+03 1.77326e+04 1.16708e+04 6.06180e+03
 3.10680e+03 3.05980e+03 4.88283e+04 3.55790e+03 1.86000e+01 2.24290e+03
 2.64870e+03 0.00000e+00 2.72500e+03 2.74630e+03 2.13000e+01 1.15758e+04
 6.18430e+03 4.17680e+03 1.57870e+03 4.36900e+02 2.15800e+02 1.19900e+02
 8.00000e+00 2.07330e+03 2.04220e+03 2.06090e+03 5.59830e+03 1.02110e+03
 4.57720e+03 2.06530e+03 2.01380e+03 2.84843e+04 8.49290e+03 1.37600e+02
 5.83400e+02 1.33000e+01 5.77100e+02 9.42100e+02 3.64900e+02 1.48730e+03
 1.07400e+02 1.18180e+03 8.90000e+00 1.80000e+00 9.55400e+02 3.95120e+03
 1.11016e+04 9.65080e+03 1.45090e+03 9.53600e+02 9.58100e+02 1.65596e+04
 2.25500e+02 4.40000e+00 6.30000e+01 1.42892e+04 1.48735e+04 5.84200e+02
 1.16490e+03 9.22500e+02 2.84000e+01 8.79000e+01 3.24100e+02 3.28500e+02
 1.03260e+03 9.98900e+02 3.37000e+01 1.67434e+04 1.38260e+04 2.60000e+01
 2.68100e+03 3.69600e+03 1.98120e+04 2.09050e+04 1.09300e+03 1.83200e+03
 1.40100e+03 2.50000e+02 1.10000e+01 3.51000e+03 7.11500e+03 7.14100e+03
 1.99710e+04 1.31440e+04 6.82700e+03 3.49900e+03 3.44600e+03 5.49920e+04
 4.00700e+03 2.10000e+01 2.52600e+03 2.98300e+03 3.06900e+03 3.09300e+03
 2.40000e+01 1.30370e+04 6.96500e+03 4.70400e+03 1.77800e+03 4.92000e+02
 2.43000e+02 1.35000e+02 9.00000e+00 2.33500e+03 2.30000e+03 2.32100e+03
 6.30500e+03 1.15000e+03 5.15500e+03 2.32600e+03 2.26800e+03 3.20800e+04
 9.56500e+03 1.55000e+02 6.57000e+02 1.50000e+01 6.50000e+02 1.06100e+03
 4.11000e+02 1.67500e+03 1.21000e+02 1.33100e+03 1.00000e+01 2.00000e+00
 1.07600e+03 4.45000e+03 1.25030e+04 1.08690e+04 1.63400e+03 1.07400e+03
 1.07900e+03 1.86500e+04 2.54000e+02 5.00000e+00 7.10000e+01 1.60930e+04
 1.67510e+04 6.58000e+02 1.31200e+03 1.03900e+03 3.20000e+01 9.90000e+01
 3.65000e+02 3.70000e+02 1.16300e+03 1.12500e+03 3.80000e+01 1.88570e+04
 1.61000e+01 3.10000e+00 4.30000e+00 2.44000e+01 1.30000e+00 2.10000e+00
 1.60000e+00 3.00000e-01 4.10000e+00 8.30000e+00 2.33000e+01 1.53000e+01
 4.00000e+00 6.42000e+01 4.70000e+00 2.90000e+00 3.50000e+00 3.60000e+00
 1.52000e+01 8.10000e+00 5.50000e+00 6.00000e-01 2.00000e-01 2.70000e+00
 7.40000e+00 6.00000e+00 2.60000e+00 3.74000e+01 1.12000e+01 8.00000e-01
 1.20000e+00 5.00000e-01 1.00000e-01 5.20000e+00 1.46000e+01 1.27000e+01
 1.90000e+00 2.18000e+01 1.88000e+01 1.95000e+01 1.50000e+00 4.00000e-01
 1.40000e+00 2.20000e+01]


Unikátne hodnoty v stĺpci 1994:
[        nan 1.33037e+04 3.65000e+01 2.55760e+03 3.50750e+03 2.00267e+04
 2.11571e+04 1.13040e+03 1.54630e+03 1.56840e+03 2.48700e+02 5.67000e+01
 3.73220e+03 7.13690e+03 7.17340e+03 1.95205e+04 1.27131e+04 6.80750e+03
 3.67550e+03 3.63810e+03 5.45461e+04 3.84460e+03 2.59000e+01 2.43270e+03
 3.51610e+03 0.00000e+00 4.72500e+02 2.39530e+03 2.41350e+03 1.82000e+01
 1.35630e+04 6.40310e+03 5.90370e+03 1.92950e+03 4.90800e+02 2.43000e+02
 1.19100e+02 2.41740e+03 2.51340e+03 2.53930e+03 6.29460e+03 1.19480e+03
 5.09980e+03 2.38090e+03 2.33380e+03 3.26562e+04 9.20750e+03 1.24900e+02
 5.36900e+02 1.21000e+02 6.83800e+02 1.10540e+03 4.21600e+02 1.59050e+03
 1.10400e+02 1.28980e+03 8.60000e+00 7.70000e+00 1.16790e+03 4.26430e+03
 1.20427e+04 1.03581e+04 1.68460e+03 1.14960e+03 1.15920e+03 1.80059e+04
 2.51600e+02 1.06000e+01 4.80000e+01 1.69476e+04 1.76381e+04 6.90500e+02
 1.12660e+03 9.99800e+02 2.69000e+01 1.90000e+00 1.46900e+02 3.59200e+02
 3.69800e+02 1.18320e+03 1.16020e+03 2.31000e+01 1.45000e+02 1.95810e+04
 1.38520e+04 3.80000e+01 2.66300e+03 3.65200e+03 2.08520e+04 2.20290e+04
 1.17700e+03 1.61000e+03 1.63300e+03 2.59000e+02 5.90000e+01 3.88600e+03
 7.43100e+03 7.46900e+03 2.03250e+04 1.32370e+04 7.08800e+03 3.82700e+03
 3.78800e+03 5.67940e+04 4.00300e+03 2.70000e+01 2.53300e+03 3.66100e+03
 4.92000e+02 2.49400e+03 2.51300e+03 1.90000e+01 1.41220e+04 6.66700e+03
 6.14700e+03 2.00900e+03 5.11000e+02 2.53000e+02 1.24000e+02 2.51700e+03
 2.61700e+03 2.64400e+03 6.55400e+03 1.24400e+03 5.31000e+03 2.47900e+03
 2.43000e+03 3.40020e+04 9.58700e+03 1.30000e+02 5.59000e+02 1.26000e+02
 7.12000e+02 1.15100e+03 4.39000e+02 1.65600e+03 1.15000e+02 1.34300e+03
 9.00000e+00 8.00000e+00 1.21600e+03 4.44000e+03 1.25390e+04 1.07850e+04
 1.75400e+03 1.19700e+03 1.20700e+03 1.87480e+04 2.62000e+02 1.10000e+01
 5.00000e+01 1.76460e+04 1.83650e+04 7.19000e+02 1.17300e+03 1.04100e+03
 2.80000e+01 2.00000e+00 1.53000e+02 3.74000e+02 3.85000e+02 1.23200e+03
 1.20800e+03 2.40000e+01 1.51000e+02 2.03880e+04 1.53000e+01 2.90000e+00
 4.00000e+00 2.30000e+01 2.43000e+01 1.30000e+00 1.80000e+00 3.00000e-01
 1.00000e-01 4.30000e+00 8.20000e+00 2.24000e+01 1.46000e+01 7.80000e+00
 4.20000e+00 6.26000e+01 4.40000e+00 2.80000e+00 5.00000e-01 2.70000e+00
 1.56000e+01 7.30000e+00 6.80000e+00 2.20000e+00 6.00000e-01 7.20000e+00
 1.40000e+00 5.90000e+00 3.75000e+01 8.00000e-01 1.50000e+00 4.90000e+00
 1.38000e+01 1.19000e+01 2.07000e+01 1.94000e+01 2.02000e+01 1.10000e+00
 2.00000e-01 4.00000e-01 2.25000e+01]


Unikátne hodnoty v stĺpci 1995:
[2.22459e+04 2.55614e+04 9.92900e+02 ... 1.69000e+01 2.53000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 1996:
[2.22909e+04 2.56175e+04 5.95500e+02 ... 1.87000e+01 1.94000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 1997:
[2.17033e+04 2.56730e+04 6.49400e+02 ... 1.87000e+01 1.85000e+01
 1.64000e+01]


Unikátne hodnoty v stĺpci 1998:
[ 2.23253e+04  2.63875e+04  1.15330e+03 ...  1.51000e+01 -8.00000e-01
  2.23000e+01]


Unikátne hodnoty v stĺpci 1999:
[2.34090e+04 2.77729e+04 1.29250e+03 ... 1.85000e+01 2.28000e+01
 1.65000e+01]


Unikátne hodnoty v stĺpci 2000:
[2.38174e+04 2.88182e+04 1.45090e+03 ... 1.48000e+01 1.82000e+01
 2.22000e+01]


Unikátne hodnoty v stĺpci 2001:
[2.42556e+04 3.01050e+04 1.36400e+03 ... 1.20000e+01 1.93000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 2002:
[2.47676e+04 3.23207e+04 1.61840e+03 ... 2.31000e+01 2.08000e+01
 1.93000e+01]


Unikátne hodnoty v stĺpci 2003:
[2.53777e+04 3.36526e+04 1.87800e+03 ... 1.84000e+01 1.91000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 2004:
[2.62015e+04 3.46624e+04 2.06220e+03 ... 1.76000e+01 1.49000e+01
 1.53000e+01]


Unikátne hodnoty v stĺpci 2005:
[2.79294e+04 3.64698e+04 2.21260e+03 ... 2.05000e+01 1.54000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 2006:
[2.89979e+04 3.80428e+04 2.33700e+03 ... 7.40000e+00 1.66000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 2007:
[2.98356e+04 3.96682e+04 2.74340e+03 ... 1.55000e+01 1.73000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 2008:
[3.12697e+04 4.19416e+04 3.27940e+03 ... 1.95000e+01 1.50000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 2009:
[3.25323e+04 4.39769e+04 3.49820e+03 ... 2.12000e+01 1.76000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 2010:
[3.30408e+04 4.52982e+04 3.45900e+03 ... 1.59000e+01 2.00000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 2011:
[3.34045e+04 4.71689e+04 3.56730e+03 ... 2.13000e+01 1.93000e+01
 2.59000e+01]


Unikátne hodnoty v stĺpci 2012:
[3.42184e+04 4.91502e+04 3.63180e+03 ... 1.84000e+01 1.76000e+01
 2.01000e+01]


Unikátne hodnoty v stĺpci 2013:
[3.46315e+04 5.06944e+04 3.97580e+03 ... 1.78000e+01 1.80000e+01
 1.65000e+01]


Unikátne hodnoty v stĺpci 2014:
[3.53591e+04 5.21736e+04 4.07210e+03 ... 1.85000e+01 1.94000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 2015:
[3.67683e+04 5.23300e+04 4.26830e+03 ... 2.63000e+01 1.41000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 2016:
[3.79912e+04 5.36197e+04 4.34120e+03 ... 1.66000e+01 1.67000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 2017:
[3.91086e+04 5.53100e+04 4.79830e+03 ... 1.99000e+01 1.92000e+01
 2.60000e+01]


Unikátne hodnoty v stĺpci 2018:
[4.03634e+04 5.68714e+04 5.32750e+03 ... 1.60000e+01 1.47000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 2019:
[4.18439e+04 5.87681e+04 6.14090e+03 ... 1.57000e+01 1.78000e+01
 1.59000e+01]


Unikátne hodnoty v stĺpci 2020:
[4.31636e+04 6.04867e+04 6.64200e+03 ... 2.12000e+01 1.59000e+01
 1.00000e+02]


Unikátne hodnoty v stĺpci 2021:
[4.48283e+04 6.26912e+04 7.88200e+03 ... 2.36000e+01 1.92000e+01
 2.73000e+01]


Unikátne hodnoty v stĺpci 2022:
[4.65011e+04 6.80253e+04 8.65430e+03 ... 2.08000e+01 1.55000e+01
 1.89000e+01]

In [41]:
#odstránenie stlpca freq
df = df.drop(columns=['freq'])
df

,unit,sector,na_item,geo\TIME_PERIOD,1990,1991,1992,1993,1994,1995,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
82634,MIO_EUR,S13,D1,AT,NaN,NaN,NaN,NaN,NaN,22245.9,...,34631.5,35359.1,36768.3,37991.2,39108.6,40363.4,41843.9,43163.6,44828.3,46501.1
82635,MIO_EUR,S13,D1,BE,NaN,NaN,NaN,NaN,NaN,25561.4,...,50694.4,52173.6,52330.0,53619.7,55310.0,56871.4,58768.1,60486.7,62691.2,68025.3
82636,MIO_EUR,S13,D1,BG,NaN,NaN,NaN,NaN,NaN,992.9,...,3975.8,4072.1,4268.3,4341.2,4798.3,5327.5,6140.9,6642.0,7882.0,8654.3
82637,MIO_EUR,S13,D1,CH,NaN,NaN,NaN,NaN,NaN,19755.3,...,38898.3,40103.8,46401.5,46011.1,45820.9,44715.3,47352.7,50531.0,51343.5,56484.6
82638,MIO_EUR,S13,D1,CY,NaN,NaN,NaN,NaN,NaN,888.5,...,2596.4,2343.1,2281.9,2270.3,2365.0,2484.2,2737.7,2900.9,2997.6,3179.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266118,PC_TOT,S1313,P3,MT,NaN,NaN,NaN,NaN,NaN,100.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1266119,PC_TOT,S1313,P31,MT,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN
1266120,PC_TOT,S1313,P32,MT,NaN,NaN,NaN,NaN,NaN,100.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1266121,PC_TOT,S1313,P5,MT,NaN,NaN,NaN,NaN,NaN,100.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1266122,PC_TOT,S1313,P51G,MT,NaN,NaN,NaN,NaN,NaN,100.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0

In [42]:
#premenovanie stlpca na country_code - to by malo byť všade
df = df.rename(columns={"geo\TIME_PERIOD": "country_code"})
df

<>:2: SyntaxWarning: invalid escape sequence '\T'
<>:2: SyntaxWarning: invalid escape sequence '\T'
C:\Users\Diana Fábiková\AppData\Local\Temp\ipykernel_31844\2503788289.py:2: SyntaxWarning: invalid escape sequence '\T'
  df = df.rename(columns={"geo\TIME_PERIOD": "country_code"})

,unit,sector,na_item,country_code,1990,1991,1992,1993,1994,1995,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
82634,MIO_EUR,S13,D1,AT,NaN,NaN,NaN,NaN,NaN,22245.9,...,34631.5,35359.1,36768.3,37991.2,39108.6,40363.4,41843.9,43163.6,44828.3,46501.1
82635,MIO_EUR,S13,D1,BE,NaN,NaN,NaN,NaN,NaN,25561.4,...,50694.4,52173.6,52330.0,53619.7,55310.0,56871.4,58768.1,60486.7,62691.2,68025.3
82636,MIO_EUR,S13,D1,BG,NaN,NaN,NaN,NaN,NaN,992.9,...,3975.8,4072.1,4268.3,4341.2,4798.3,5327.5,6140.9,6642.0,7882.0,8654.3
82637,MIO_EUR,S13,D1,CH,NaN,NaN,NaN,NaN,NaN,19755.3,...,38898.3,40103.8,46401.5,46011.1,45820.9,44715.3,47352.7,50531.0,51343.5,56484.6
82638,MIO_EUR,S13,D1,CY,NaN,NaN,NaN,NaN,NaN,888.5,...,2596.4,2343.1,2281.9,2270.3,2365.0,2484.2,2737.7,2900.9,2997.6,3179.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266118,PC_TOT,S1313,P3,MT,NaN,NaN,NaN,NaN,NaN,100.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1266119,PC_TOT,S1313,P31,MT,NaN,NaN,NaN,NaN,NaN,NaN,...,100.0,100.0,100.0,100.0,100.0,100.0,NaN,NaN,NaN,NaN
1266120,PC_TOT,S1313,P32,MT,NaN,NaN,NaN,NaN,NaN,100.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1266121,PC_TOT,S1313,P5,MT,NaN,NaN,NaN,NaN,NaN,100.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
1266122,PC_TOT,S1313,P51G,MT,NaN,NaN,NaN,NaN,NaN,100.0,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0

In [43]:
#Unpivotovanie dát pomocou melt
df_melted = pd.melt(df, 
                    id_vars=['unit', 'sector', 'na_item', 'country_code'],  #Stĺpce, ktoré chceme ponechať
                    var_name='year',   #Nový stĺpec, kde budu vsetky roky
                    value_name='value'  #Nový stĺpec pre hodnoty z rokov - teda tá výška investície buď ako percento alebo v milionoch eur
                   )

# Zobrazenie výsledkov
df_melted

           unit sector na_item country_code  year  value
0       MIO_EUR    S13      D1           AT  1990    NaN
1       MIO_EUR    S13      D1           BE  1990    NaN
2       MIO_EUR    S13      D1           BG  1990    NaN
3       MIO_EUR    S13      D1           CH  1990    NaN
4       MIO_EUR    S13      D1           CY  1990    NaN
...         ...    ...     ...          ...   ...    ...
497437   PC_TOT  S1313      P3           MT  2022  100.0
497438   PC_TOT  S1313     P31           MT  2022    NaN
497439   PC_TOT  S1313     P32           MT  2022  100.0
497440   PC_TOT  S1313      P5           MT  2022  100.0
497441   PC_TOT  S1313    P51G           MT  2022  100.0

[497442 rows x 6 columns]

In [44]:
#ešte som zabudla na stlpec na_item, pozriem sa, čo v ňom je
unique_values = df['na_item'].unique()

#vytlačenie unikátnych hodnôt
print(unique_values)

#zistím, že chcem len TE - total government expenditure

['D1' 'D29_D5_D8' 'D3' 'D4' 'D4_S1311' 'D4_S1312' 'D4_S1313' 'D4_S1314'
 'D62' 'D62_D632' 'D632' 'D7' 'D7_S1311' 'D7_S1312' 'D7_S1313' 'D7_S1314'
 'D9' 'D92' 'D9_S1311' 'D9_S1312' 'D9_S1313' 'D9_S1314' 'NP' 'OP5ANP' 'P2'
 'P2_D29_D5_D8' 'P3' 'P31' 'P32' 'P5' 'P51G' 'TE']

In [45]:
#filtrovanie riadkov, kde v stĺpci 'na_item' je hodnota 'TE'
#to isté spravím pre stlpec sector, kde zistím, že chcem len S13 (alebo sa to dá čeknúť aj na eurostat webovom datasete)
#tu si už vyfilturujem, že v stlpci sector chcem len S13 (general government) - je to sporné, lebo aj local governments investujú, ale whatever, nás zaujíma len general
filtered_df = df_melted[(df_melted['na_item'] == 'TE') & (df_melted['sector'] == 'S13')] 

#Zobrazenie výsledkov
filtered_df

           unit sector na_item country_code  year  value
1023    MIO_EUR    S13      TE           AT  1990    NaN
1024    MIO_EUR    S13      TE           BE  1990    NaN
1025    MIO_EUR    S13      TE           BG  1990    NaN
1026    MIO_EUR    S13      TE           CH  1990    NaN
1027    MIO_EUR    S13      TE           CY  1990    NaN
...         ...    ...     ...          ...   ...    ...
493433   PC_GDP    S13      TE           PT  2022   44.1
493434   PC_GDP    S13      TE           RO  2022   40.0
493435   PC_GDP    S13      TE           SE  2022   48.9
493436   PC_GDP    S13      TE           SI  2022   47.2
493437   PC_GDP    S13      TE           SK  2022   42.3

[3267 rows x 6 columns]

In [46]:
# Filtrovanie riadkov, kde v 'unit' nie je 'MIO_NAC'
prefinal_df = filtered_df[filtered_df['unit'] != 'MIO_NAC']

# Zobrazenie výsledkov
prefinal_df

           unit sector na_item country_code  year  value
1023    MIO_EUR    S13      TE           AT  1990    NaN
1024    MIO_EUR    S13      TE           BE  1990    NaN
1025    MIO_EUR    S13      TE           BG  1990    NaN
1026    MIO_EUR    S13      TE           CH  1990    NaN
1027    MIO_EUR    S13      TE           CY  1990    NaN
...         ...    ...     ...          ...   ...    ...
493433   PC_GDP    S13      TE           PT  2022   44.1
493434   PC_GDP    S13      TE           RO  2022   40.0
493435   PC_GDP    S13      TE           SE  2022   48.9
493436   PC_GDP    S13      TE           SI  2022   47.2
493437   PC_GDP    S13      TE           SK  2022   42.3

[2178 rows x 6 columns]

In [47]:
#ROZHODLA SOM SA, ŽE NEDÁM PREČ NULOVE HODNOTY
#na záver ešte dám preč NaN hodnoty zo stlpca value
#final_df= prefinal_df.dropna(subset='value')
#final_df

prefinal_df

           unit sector na_item country_code  year  value
1023    MIO_EUR    S13      TE           AT  1990    NaN
1024    MIO_EUR    S13      TE           BE  1990    NaN
1025    MIO_EUR    S13      TE           BG  1990    NaN
1026    MIO_EUR    S13      TE           CH  1990    NaN
1027    MIO_EUR    S13      TE           CY  1990    NaN
...         ...    ...     ...          ...   ...    ...
493433   PC_GDP    S13      TE           PT  2022   44.1
493434   PC_GDP    S13      TE           RO  2022   40.0
493435   PC_GDP    S13      TE           SE  2022   48.9
493436   PC_GDP    S13      TE           SI  2022   47.2
493437   PC_GDP    S13      TE           SK  2022   42.3

[2178 rows x 6 columns]

In [48]:
#Zobrazenie počtu unikátnych hodnôt v jednotlivých stĺpcoch, uistím sa, že mám všade, to, čo chcem
print(prefinal_df.nunique())

#Zobrazenie konkrétnych unikátnych hodnôt pre každý stĺpec
for column in prefinal_df.columns:
    print(f"Unikátne hodnoty v stĺpci {column}:")
    print(prefinal_df[column].unique())
    print("\n")

unit               2
sector             1
na_item            1
country_code      33
year              33
value           1196
dtype: int64
Unikátne hodnoty v stĺpci unit:
['MIO_EUR' 'PC_GDP']


Unikátne hodnoty v stĺpci sector:
['S13']


Unikátne hodnoty v stĺpci na_item:
['TE']


Unikátne hodnoty v stĺpci country_code:
['AT' 'BE' 'BG' 'CH' 'CY' 'CZ' 'DE' 'DK' 'EA19' 'EA20' 'EE' 'EL' 'ES'
 'EU27_2020' 'FI' 'FR' 'HR' 'HU' 'IE' 'IS' 'IT' 'LT' 'LU' 'LV' 'MT' 'NL'
 'NO' 'PL' 'PT' 'RO' 'SE' 'SI' 'SK']


Unikátne hodnoty v stĺpci year:
['1990' '1991' '1992' '1993' '1994' '1995' '1996' '1997' '1998' '1999'
 '2000' '2001' '2002' '2003' '2004' '2005' '2006' '2007' '2008' '2009'
 '2010' '2011' '2012' '2013' '2014' '2015' '2016' '2017' '2018' '2019'
 '2020' '2021' '2022']


Unikátne hodnoty v stĺpci value:
[        nan 5.33332e+04 4.79000e+01 ... 4.63347e+04 5.83000e+01
 2.12000e+01]

In [49]:
#odstránenie stlpcov sector a na_item. V sector mám len to S13, čo je šport a niečo - je to na eurostate a v na_item mám len TE, čiže tie celkové vládne výdavky
prefinal_df = prefinal_df.drop(columns=['sector', 'na_item'])
prefinal_df

           unit country_code  year  value
1023    MIO_EUR           AT  1990    NaN
1024    MIO_EUR           BE  1990    NaN
1025    MIO_EUR           BG  1990    NaN
1026    MIO_EUR           CH  1990    NaN
1027    MIO_EUR           CY  1990    NaN
...         ...          ...   ...    ...
493433   PC_GDP           PT  2022   44.1
493434   PC_GDP           RO  2022   40.0
493435   PC_GDP           SE  2022   48.9
493436   PC_GDP           SI  2022   47.2
493437   PC_GDP           SK  2022   42.3

[2178 rows x 4 columns]

In [50]:
prefinal_df['value'] = prefinal_df['value'].astype(float)

In [51]:
prefinal_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2178 entries, 1023 to 493437
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   unit          2178 non-null   object
 1   country_code  2178 non-null   object
 2   year          2178 non-null   object
 3   value         1852 non-null   float64
dtypes: float64(1), object(3)
memory usage: 85.1+ KB

In [53]:
prefinal_df['value'] = prefinal_df['value'].astype(str).str.replace('.', ',', regex=False)

In [55]:
prefinal_df['value'] = prefinal_df['value'].astype(str).str.replace('nan', '0')

In [56]:
#export do csv
prefinal_df.to_csv("gov_expenditure_final2.csv", index=False)